Models/BusTrip.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BTRS.Models
{
	[Index(nameof(BusTrip.BusNumber), IsUnique = true)]
	public class BusTrip
    {
        [Key]
        public int BusTripID { get; set; }
        [Required]
        public string TripDistination { get; set; }
        [Required]
        public DateTime StartDate { get; set; }
        [Required]
        public DateTime EndDate { get; set; }
        [Required]
        public int BusNumber { get; set; }

        public ICollection<Passenger_BusTrip> passenger_BusTrip { get; set; }
        public ICollection<Bus> bus { get; set; }

        [ForeignKey("AdminID")]
        public Admin admin { get; set; }

        

    }
}

Controllers/BusController.cs
using BTRS.Data;
using BTRS.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BTRS.Controllers
{
    public class BusController : Controller
    {
        private SystemDbContext _context;
        public BusController(SystemDbContext context)
        {
            this._context = context;
        }
        // GET: BusController
        public ActionResult Index()
        {
            return View(_context.bus.ToList());
        }

        // GET: BusController/Details/5
        public ActionResult Details(int id)
        {
			Bus bus = _context.bus.Find(id);
            return View(bus);
		}

        // GET: BusController/Create
        public ActionResult Create()
        {
            ViewBag.BusTrip = _context.busTrip.ToList();
            return View();
        }

        // POST: BusController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection form)
        {
            int adminid = (int)HttpContext.Session.GetInt32("adminID");

            Admin admin = _context.admin.Where(
                  a => a.AdminID == adminid
                  ).FirstOrDefault();

            string CaptinName = form["CaptinName"];
            int NumberOfSeats = int.Parse(form["NumberOfSeats"]);
            int BusTripID = int.Parse(form["BusTripID"]);

            Bus bus = new Bus();
            bus.CaptinName = CaptinName;
            bus.NumberOfSeats = NumberOfSeats;
            bus.bustrip = _context.busTrip.Find(BusTripID);

            bus.admin = admin;

            _context.bus.Add(bus);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: BusController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.BusTrip = _context.busTrip.ToList();
			Bus bus = _context.bus.Find(id);
			return View(bus);
        }

        // POST: BusController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection form)
        {
            int adminid = (int)HttpContext.Session.GetInt32("adminID");

            Admin admin = _context.admin.Where(
                  a => a.AdminID == adminid
                  ).FirstOrDefault();

            string CaptinName = form["CaptinName"];
            int NumberOfSeats = int.Parse(form["NumberOfSeats"]);
            int BusTripID = int.Parse(form["BusTripID"]);

            Bus bus = _context.bus.Find(id);
            bus.CaptinName = CaptinName;
            bus.NumberOfSeats = NumberOfSeats;
            bus.bustrip = _context.busTrip.Find(BusTripID);

            bus.admin = admin;

            _context.bus.Update(bus);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: BusController/Delete/5
        public ActionResult Delete(int id)
        {
            Bus bus = _context.bus.Find(id);
            return View(bus);
        }

        // POST: BusController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id,Bus bus)
        {
            try
            {
                _context.bus.Remove(bus);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/BusTripController.cs
using BTRS.Data;
using BTRS.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BTRS.Controllers
{
	public class BusTripController : Controller
	{
		private SystemDbContext _context;

		public BusTripController(SystemDbContext context)
		{
			this._context = context;
		}

		// GET: BusTrip
		public ActionResult Index()
		{

			return View(_context.busTrip.ToList());
		}

		// GET: BusTrip/Details/5
		public ActionResult Details(int id)
		{
			BusTrip bustrip=_context.busTrip.Find(id);

			return View(bustrip);
		}

		// GET: BusTrip/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: BusTrip/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(BusTrip bustrip)
		{
			int adminID =(int)HttpContext.Session.GetInt32("adminID");

			Admin admin = _context.admin.Where(a => a.AdminID==adminID).FirstOrDefault();

			bustrip.admin = admin;

			_context.busTrip.Add(bustrip);
			_context.SaveChanges();
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: BusTrip/Edit/5
		public ActionResult Edit(int id)
		{
			BusTrip bustrip = _context.busTrip.Find(id);

			return View(bustrip);
		}

		// POST: BusTrip/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection form)
		{
			int adminid = (int)HttpContext.Session.GetInt32("adminID");

			Admin admin = _context.admin.Where(
				  a => a.AdminID == adminid
				  ).FirstOrDefault();

			string TripDistination = form["TripDistination"];
			DateTime StartDate = DateTime.Parse(form["StartDate"]);
			DateTime EndDate = DateTime.Parse(form["EndDate"]);
			int BusNumber = int.Parse(form["BusNumber"]);

			BusTrip bustrip=_context.busTrip.Find(id);
			bustrip.TripDistination = TripDistination; 
			bustrip.BusNumber = BusNumber;
			bustrip.StartDate = StartDate;
			bustrip.EndDate = EndDate;

			bustrip.admin = admin;

			_context.busTrip.Update(bustrip);
			_context.SaveChanges();

			return RedirectToAction("Index");


			
		}

		// GET: BusTrip/Delete/5
		public ActionResult Delete(int id)
		{
			BusTrip bustrip = _context.busTrip.Find(id);
			return View(bustrip);
		}

		// POST: BusTrip/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, BusTrip bustrip)
		{
			try
			{
				_context.busTrip.Remove(bustrip); 
				_context.SaveChanges();
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

Views/BusTrip/Create.cshtml
@model BTRS.Models.BusTrip

@{
    ViewData["Title"] = "Create";
}

<h1>Add New Trip</h1>

<h4>BusTrip</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TripDistination" class="control-label"></label>
                <input asp-for="TripDistination" class="form-control" />
                <span asp-validation-for="TripDistination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusNumber" class="control-label"></label>
                <input asp-for="BusNumber" class="form-control" />
                <span asp-validation-for="BusNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BusTrip/Delete.cshtml
@model BTRS.Models.BusTrip

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BusTrip</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TripDistination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TripDistination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BusTripID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/BusTrip/Details.cshtml
@model BTRS.Models.BusTrip

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BusTrip</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TripDistination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TripDistination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BusTripID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/BusTrip/Edit.cshtml
@model BTRS.Models.BusTrip

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BusTrip</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BusTripID" />
            <div class="form-group">
                <label asp-for="TripDistination" class="control-label"></label>
                <input asp-for="TripDistination" class="form-control" />
                <span asp-validation-for="TripDistination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusNumber" class="control-label"></label>
                <input asp-for="BusNumber" class="form-control" />
                <span asp-validation-for="BusNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BusTrip/Index.cshtml
@model IEnumerable<BTRS.Models.BusTrip>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-action="Index" asp-controller="Bus">Go To Bus</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TripDistination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TripDistination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BusTripID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BusTripID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BusTripID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>