Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace BTRS.Models
{
	public class Login
	{
		[Required(ErrorMessage = "Please Enter Username")]
		public String Username { get; set; }
		[Required(ErrorMessage = "Please Enter Password")]
		public String Password { get; set; }
	}
}

Models/Passenger.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace BTRS.Models
{
    
    [Index(nameof(Passenger.UserName), IsUnique = true)]
    [Index(nameof(Passenger.PhoneNumber), IsUnique = true)]
    [Index(nameof(Passenger.EmailAddress),IsUnique =true)]
    public class Passenger
    {
        
        [Key]
        public int PassengerID { get; set; }
        [Required(ErrorMessage ="Please Enter your Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter your Email")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Please Enter a Password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please Enter your Gender")]
        public string Gender { get; set; }
		public enum gender
		{
			Male,
			Female
		}
		[Required(ErrorMessage = "Please Enter a UserName")]
        public string UserName { get; set; }
        public int PhoneNumber { get; set; }

        public ICollection<Passenger_BusTrip> passenger_BusTrip { get; set; }
    }
}

Controllers/PassengerController.cs
using BTRS.Data;
using BTRS.Models;
using Humanizer.Localisation.TimeToClockNotation;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;

namespace BTRS.Controllers
{
    public class PassengerController : Controller
    {

        private SystemDbContext _context;

        public PassengerController(SystemDbContext context)
        {
            this._context= context;
        }
        
		public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult SignUp() 
        {
            return View();
        }
		
		[HttpPost]
        public IActionResult SignUp(Passenger passenger)
        {
            bool Empty = CheckEmpty(passenger);
            bool duplicate = CheckDuplicate(passenger.UserName,passenger.EmailAddress,passenger.PhoneNumber);

            if (Empty)
            {
                if (duplicate)
                {
                    _context.passenger.Add(passenger);
                    _context.SaveChanges();

                    TempData["Msg"] = "Congrats You Signed Up";
                    return View();
                }
                else
                {
                    TempData["Msg"] = "The data is Used";
                    return View();
                }
            }
            else
            {
                TempData["Msg"] = "please fill Data";
				return View();
            }
        }
		  
		public bool CheckDuplicate(String username, String emailAddress, int phoneNumber)
        {
            Passenger user = _context.passenger.Where(u=>u.UserName.Equals(username)&&
            u.EmailAddress.Equals(emailAddress) &&
            u.PhoneNumber.Equals(phoneNumber)).FirstOrDefault();

            if(user!=null)
            {
                return false;
            }
            else
            {
                return true;
            }
		}
		public bool CheckEmpty(Passenger passenger)
        {
            if (String.IsNullOrEmpty(passenger.Name)) return false;
            else if (String.IsNullOrEmpty(passenger.UserName)) return false;
            else if (String.IsNullOrEmpty(passenger.Password)) return false;
            else if (String.IsNullOrEmpty(passenger.EmailAddress)) return false;
            else if (String.IsNullOrEmpty(passenger.Gender)) return false;
            else return true;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Login login)
        {
			if (ModelState.IsValid)
            {
				String username = login.Username;
				String password = login.Password;

				Passenger passenger = _context.passenger.Where(u => u.UserName.Equals(username) &&
				u.Password.Equals(password)).FirstOrDefault();

                Admin admin = _context.admin.Where(a=> a.UserName.Equals(username) &&
				a.Password.Equals(password)).FirstOrDefault();

				if (passenger!=null)
                {
                    HttpContext.Session.SetInt32("PassengerID",passenger.PassengerID );
                    return RedirectToAction("BusTripList");
                }
                else if(admin!=null)
                {
                    HttpContext.Session.SetInt32("adminID",admin.AdminID);
                    return RedirectToAction("Index", "BusTrip");
                }
                else
                {
                    TempData["Msg"] = "Passenger not found";
                }
			}
            else
            {

            }
            return View();
        }

        public IActionResult BusTripList()
        {
            int passengerId = (int)HttpContext.Session.GetInt32("PassengerID");

            List<int> lst=_context.passenger_bustrip.Where(
                t => t.passenger.PassengerID == passengerId
                ).Select(s=>s.bustrip.BusTripID).ToList();

            List<BusTrip> lst_BusTrip=_context.busTrip.Where(
                t => lst.Contains(t.BusTripID)==false
                ).ToList();

            return View(lst_BusTrip);
        }

        public IActionResult SelectTrip(int id)
        {
            int BusTripID = id;
            int passengerId=(int)HttpContext.Session.GetInt32("PassengerID");

            Passenger_BusTrip passenger_bustrip=new Passenger_BusTrip();

            passenger_bustrip.passenger = _context.passenger.Find(passengerId);
            passenger_bustrip.bustrip = _context.busTrip.Find(BusTripID);

            _context.passenger_bustrip.Add(passenger_bustrip);
            _context.SaveChanges();

            return RedirectToAction("ListTrips");
        }


        public IActionResult ListTrips()
        {
            int passengerId = (int)HttpContext.Session.GetInt32("PassengerID");

            List<int> lst_BusTrip=_context.passenger_bustrip.Where(
                t => t.passenger.PassengerID == passengerId
                ).Select(s=>s.bustrip.BusTripID).ToList();

            List<BusTrip> lst = _context.busTrip.Where(
                t => lst_BusTrip.Contains(t.BusTripID)
                ).ToList();

            return View(lst);
        }
        
        public IActionResult CancleTrip(int BusTripID)
        {
            int passengerId = (int)HttpContext.Session.GetInt32("PassengerID");

            Passenger_BusTrip passenger_BusTrip=_context.passenger_bustrip.Where(
                t => t.passenger.PassengerID == passengerId && t.bustrip.BusTripID==BusTripID
                ).FirstOrDefault();

            _context.passenger_bustrip.Remove(passenger_BusTrip); 
            _context.SaveChanges();

            return RedirectToAction("ListTrips");
        }
    }
}

Views/Passenger/BusTripList.cshtml
@model IEnumerable<BTRS.Models.BusTrip>

@{
    ViewData["Title"] = "BusTripList";
}

<h1>BusTripList</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TripDistination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TripDistination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNumber)
            </td>
            <td>
                <a asp-action="SelectTrip" asp-route-id="@item.BusTripID" class="btn btn-danger">Select Trip</a>
            </td>
            
        </tr>
        
}
    </tbody>
    <tfoot>
        <a asp-action="ListTrips" class="btn btn-warning">My Trips</a>
    </tfoot>
</table>

Views/Passenger/ListTrips.cshtml
@model IEnumerable<BTRS.Models.BusTrip>

@{
    ViewData["Title"] = "ListTrips";
}

<h1>My Trips</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TripDistination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TripDistination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNumber)
            </td>
            <td>
                <a asp-action="CancleTrip" asp-route-BusTripID="@item.BusTripID" class="btn btn-danger">Cancle Trip</a>
            </td>
        </tr>
}
    </tbody>
    <tfoot>
        <a asp-action="BusTripList" class="btn btn-warning">Go To Available Trips</a>
    </tfoot>
</table>

Views/Passenger/Login.cshtml
@model BTRS.Models.Login;
@using static BTRS.Models.Passenger;

@using(Html.BeginForm("Login","Passenger",FormMethod.Post)){
	<table>

		<tr>
			<td>Username</td>
			<td>
				@Html.TextBox("Username",null,new{@Type="text"})
			</td>
			<td>
				@Html.ValidationMessageFor(m => m.Username)
			</td>
		</tr>
		<tr>
			<td>Password</td>
			<td>
				@Html.TextBox("Password",null,new{@Type="password"})
			</td>
			<td>
				@Html.ValidationMessageFor(m => m.Password)
			</td>
		</tr>


	</table>
	<input type="submit" value="Login" class="btn btn-primary" />
}
@Html.ActionLink("SignUp", "SignUp","Passenger", new { onclick = "SignUp;"},new { @class = "btn btn-primary" })

@TempData["Msg"]

Views/Passenger/SignUp.cshtml
@using BTRS.Models
@using static BTRS.Models.Passenger;
@model Passenger

@using(Html.BeginForm("SignUp","Passenger",FormMethod.Post)){


	<table>

		<tr>
			<td>Name</td>
			<td>
				@Html.TextBox("Name",null,new{@Type="text"})
			</td>
		</tr>
		<tr>
			<td>EmailAddress</td>
			<td>
				@Html.TextBox("EmailAddress",null,new{@Type="text"})
			</td>
		</tr>
		<tr>
			<td>UserName</td>
			<td>
				@Html.TextBox("UserName",null,new{@Type="text"})
			</td>
		</tr>
		<tr>
			<td>Password</td>
			<td>
				@Html.TextBox("Password",null,new{@Type="password"})
			</td>
		</tr>
		<tr>
			<td>PhoneNumber</td>
			<td>
				@Html.TextBox("PhoneNumber",null,new{@Type="text"})
			</td>
		</tr>
		<tr>
			<td>Gender</td>
			<td>
				@Html.DropDownList("Gender",
                   new SelectList(Enum.GetValues(typeof(gender))),
                   "Select Gender",
                    new { @class = "form-control" })
			</td>
		</tr>
	</table>

	@Html.TextBox("SignUp","SignUp",new{@Type="submit"})
}
@TempData["Msg"]